#!/usr/bin/env python
"""A1 — reports/licensing_report.md (PLAN §14 A1, §0.2: audit reduced to the license column).

v3.1 sources of the licence (build_manifest.py): catalog_<label>.json `cc` flag and/or the
yt-dlp infojson `license` string; `license_source` records which one(s) backed each row.
"""
import json
import os
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from src.data.dataset_config import load_dataset_config  # noqa: E402

MAN = "data/manifests"


def load(n):
    with open(os.path.join(MAN, n), encoding="utf-8") as f:
        return [json.loads(l) for l in f]


def main():
    cfg = load_dataset_config()
    allr = load("all.jsonl")
    bs = json.load(open(os.path.join(MAN, "all_build_stats.json"), encoding="utf-8"))
    L = []
    A = L.append
    A("# Licensing and provenance — RuLongTTS\n")
    A(f"Generated by `src/data/licensing_report.py` for dataset **{cfg['version']}** "
      f"(`{cfg['root']}`, configured in `configs/dataset.yaml`). PLAN §0.2 / decisions.md "
      "(2026-08-27, 2026-08-29): the licensing audit is reduced to the `license` column, which "
      "on v3.1 is built from `metadata/catalog_<label>.json` (`cc` flag, YouTube Data API "
      "`status.license`) and `metadata/infojson/<video_id>.info.json` (`license` string).\n")
    A("## 1. License per segment\n")
    lic = Counter(r["license"] for r in allr)
    A("| license | segments | hours | videos |")
    A("|---|---:|---:|---:|")
    for k, n in lic.most_common():
        h = sum(r["duration_sec"] for r in allr if r["license"] == k) / 3600
        v = len({r["video_id"] for r in allr if r["license"] == k})
        A(f"| `{k}` | {n} | {h:.2f} | {v} |")
    A("")
    A("## 2. Where the licence and the channel came from\n")
    A("| license_source | segments | videos |")
    A("|---|---:|---:|")
    for k, n in Counter(r["license_source"] for r in allr).most_common():
        A(f"| {k} | {n} | {len({r['video_id'] for r in allr if r['license_source'] == k})} |")
    A("")
    A(f"- catalog/infojson licence conflicts: **{len(bs.get('license_conflicts', []))}**"
      + (f" {bs['license_conflicts'][:5]}" if bs.get("license_conflicts") else ""))
    A("")
    A("| channel_source | segments | videos |")
    A("|---|---:|---:|")
    for k, n in Counter(r["channel_source"] for r in allr).most_common():
        A(f"| {k} | {n} | {len({r['video_id'] for r in allr if r['channel_source'] == k})} |")
    A("")
    unk = sorted({r["video_id"] for r in allr if r["channel_source"] == "unknown"})
    A(f"- videos with no resolvable channel (pseudo-channel `other:unknown:<video_id>`, never in "
      f"dev/test): **{len(unk)}** {unk if unk else ''}")
    A(f"- videos with a yt-dlp infojson: {bs.get('videos_with_infojson')} of {bs.get('videos')}; "
      f"videos listed in a catalog: {bs.get('videos_in_catalogs')}")
    A(f"- catalog label → YouTube channel (from infojson): "
      f"{ {k: v[1] for k, v in bs.get('label_to_youtube_channel', {}).items()} }")
    A("")
    A("## 3. Per-split license breakdown\n")
    A("| split | segments | licenses |")
    A("|---|---:|---|")
    for name in ("train_long.jsonl", "dev.jsonl", "test.jsonl"):
        rows = load(name)
        A(f"| {name} | {len(rows)} | {dict(Counter(r['license'] for r in rows))} |")
    A("")
    A("## 4. Provenance fields kept in every manifest row\n")
    A("`video_id`, `channel_id`, `channel_title`, `channel_label`, `youtube_channel_id`, "
      "`video_title`, `channel_source`, `license`, `license_source`, `license_raw`, `audio_path`, "
      "`source_root`, `start`, `end`, `sha256_audio`, `sha256_text`. "
      "The audio itself is never copied or modified by A1: the manifests reference the read-only "
      f"dataset paths under `{cfg['root']}`.\n")
    lics = set(lic)
    A("## 5. Verdict\n")
    if lics == {"creativeCommon"}:
        A(f"All {len({r['video_id'] for r in allr})} videos carry the YouTube "
          "`creativeCommon` flag (CC BY) in at least one metadata source, with no conflict "
          "between the catalog flag and the infojson string where both exist. Redistribution "
          "of audio+text with attribution is therefore permitted at the YouTube level; the "
          "`channel_title`/`video_title`/`video_id`/`youtube_channel_id` fields carry the "
          "attribution information.\n")
    else:
        A(f"Licenses present: {sorted(lics)} — non-`creativeCommon` rows must be reviewed "
          "before redistribution.\n")
    A("**Caveat carried over from the dataset README** (v3.1): part of the material is a "
      "narration of published books by third parties; a CC label on the upload does not "
      "convey rights to the underlying work. Before publishing the corpus a separate rights "
      "check and narrator consent are required (Limitations/Ethics section of the paper).")
    os.makedirs("reports", exist_ok=True)
    with open("reports/licensing_report.md", "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("wrote reports/licensing_report.md")


if __name__ == "__main__":
    main()
